# Generated by Django 6.0.6 on 2026-06-24 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_provider', models.CharField(max_length=128)),
                ('transaction_id', models.CharField(max_length=200)),
                ('amount', models.FloatField(blank=True)),
                ('payment_status', models.CharField(max_length=64)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
