# Generated by Django 5.2.18 on 2026-10-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basket',
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('CART', 'Regular Cart'), ('CONSOLIDATED_BASKET', 'Consolidated Basket')], default='CONSOLIDATED_BASKET', max_length=25),
        ),
    ]
