# Generated by Django 5.2.18 on 2026-10-10 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_basket_order_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    migrations.AlterField(
        model_name='order',
        name='buyer',
        field=models.ForeignKey(
            on_delete=django.db.models.deletion.PROTECT,
            related_name='orders',
            to=settings.AUTH_USER_MODEL,
        ),
    ),
    ]
