# Generated by Django 5.2.18 on 2026-10-10 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_alter_basketitem_basket_and_more'),
        ('orders', '0004_alter_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='basket.consolidatedbasket'),
        ),
    ]
