# Generated by Django 5.2.18 on 2026-10-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_consolidatedbasket_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='expected_godown_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='shipping_status',
            field=models.CharField(choices=[('IN_BASKET', 'In Basket'), ('IN_TRANSIT', 'Shipping to Godown'), ('AT_GODOWN', 'Arrived at Godown')], default='IN_BASKET', max_length=20),
        ),
    ]
