# Generated by Django 5.2.18 on 2026-10-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_basketitem_confirmed_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='basketitem',
            name='unique_product_per_basket',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='price_at_addition',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='quantity',
        ),
    ]
