# Generated by Django 6.0.6 on 2026-06-26 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSNCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_picturs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GSTRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(null=True)),
                ('hsn_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.hsncode')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('brancd', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.FloatField(blank=True)),
                ('description', models.CharField(max_length=1024)),
                ('delivery_days', models.IntegerField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('hsn_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.hsncode')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.seller')),
            ],
        ),
    ]
