# Generated by Django 6.0.6 on 2026-06-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_picturs',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product_picturs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
